sign up, sign in and edit profile
otuhs-r/e-navigator pull request #1
Opened 2018-05-07 13:09 UTC by otuhs-r

## やりたかったこと

* ユーザー登録/削除、ログイン/ログアウト機能の追加
* 登録したユーザーのプロフィール編集機能の追加

## やったこと

* Devise gem の導入
	* (認証用)メール送信
* 簡易的なトップページの追加
* プロフィール確認画面の追加
* プロフィール編集画面の追加
* Bootstrapの導入

## 動作確認方法

- [ ] ユーザーを新規で登録する
- [ ] 認証メールから認証する(メール記載のリンクをクリック)
- [ ] 画面右上「Profile」より、プロフィール確認画面へいく
- [ ] 「Edit」より、プロフィール編集画面へいく
- [ ] 編集内容の記入後、「Update」より編集を完了する
- [ ]  画面右上「Sign out」より、ログアウトする
- [ ] ログアウト後、再度ログインする
- [ ] プロフィール編集画面左下「Cancel my account」より、ユーザーの削除
## その他

特になし。

2018-05-08 05:10 UTC, pokotyamu commented
見ます 👀

2018-05-08 05:13 UTC, pokotyamu commented
コミットメッセージの頭に prefix 付けているの良いですね 👍 
これって何か参考にされたんですか？

2018-05-08 05:35 UTC, pokotyamu requested changes
ルーティングがちょっと不思議な感じがします。
ユーザー個人の編集ページなのに、 `/users/edit` となっているのはユーザー全体を編集している感じがしますね。
また、ユーザー個人の詳細ページも `/show.1` となっているのは意図的でしょうか？
(このままだと面接オブジェクトを作った際、 `/show` だと何を表示しているか分からなくならないですか？)

---

Rails の基本的な思想として RESTful というものがあります。
今のままだと、 User へのアクセスがパット見で分からない感じになってしまうので、ルーティング関係の修正をよろしくお願いします！
https://qiita.com/kidach1/items/43e53811c12351915278

2018-05-08 05:35 UTC, pokotyamu commented on .gitignore
> +.env
.env は各プロジェクトで定義しても良いんですが、他のプロジェクトに移った際に誤ってコミットしちゃう可能性もあるので、 gitignore_global に追加しておくとより安全ですよ！

2018-05-08 05:35 UTC, pokotyamu commented on app/controllers/pages_controller.rb
> +end
ちなみに PagesController って今後どんな拡張をする予定ですか？ 🤔

2018-05-08 05:38 UTC, pokotyamu commented
認証時にメールを送るのいいですね！
`.env` ファイルでしっかりセキュリティ面も担保しているの良いと思います 👍

2018-05-08 05:41 UTC, pokotyamu commented on config/routes.rb
> +  end
letter_opener の導入いいですね 👍

2018-05-09 07:12 UTC, otuhs-r commented on .gitignore
> +.env
ありがとうございます。便利なものがあるんですね！gitignore_globalに追加しました。

2018-05-09 07:12 UTC, otuhs-r commented on app/controllers/pages_controller.rb
> +end
Railsでの開発が初めてなので、記事を参考に見よう見まねで作っていたモノです。。。
特に拡張の予定もないので削除します。

2018-05-09 07:13 UTC, otuhs-r commented
レビューありがとうございます。

---

> コミットメッセージの頭に prefix 付けているの良いですね 👍
これって何か参考にされたんですか？

Qiitaの[【今日からできる】コミットメッセージに 「プレフィックス」 をつけるだけで、開発効率が上がった話](https://qiita.com/numanomanu/items/45dd285b286a1f7280ed)という記事を参考に付けてみました。

---

ルーティングについて

> ルーティングがちょっと不思議な感じがします。
ユーザー個人の編集ページなのに、 /users/edit となっているのはユーザー全体を編集している感じがしますね。

deviseの`devise_for`メソッドによるデフォルトのルーティングを用いた結果そうなっています。
重厚なライブラリを使う弊害?と割り切るしかないかと思っていたのですが、きれいに設定するための参考記事などあればご教示いただきたいです。(自分でも探してみましたが見つけられませんでした。。。)

> また、ユーザー個人の詳細ページも /show.1 となっているのは意図的でしょうか？
(このままだと面接オブジェクトを作った際、 /show だと何を表示しているか分からなくならないですか？)

後先のことを考えた作りにできていませんでした。ユーザー(自分自身)のページだとわかるように修正します。

2018-05-10 05:42 UTC, pokotyamu commented
> deviseのdevise_forメソッドによるデフォルトのルーティングを用いた結果そうなっています。

なるほどなるほど
１つ案としてあげるなら、 `devise_for` の `devise/registrations#update` 他にユーザーの `users#update` を用意して、名前や生年月日についてはそちらで更新処理をやっちゃうとかですかね 👀 

デバイスのルーティングに乗っかるというのも１つの道ですが、アップデートなどで破壊的な変更があった際に動かなくなる恐れがありますね 🤔 

ここ、現状の動きとしては問題ないので、次に進んでもいいかとは思いますが、修正やってみますか？

2018-05-10 05:48 UTC, pokotyamu commented
> 後先のことを考えた作りにできていませんでした。ユーザー(自分自身)のページだとわかるように修正します。

他の Qiita 記事などを参考にされるのは非常に良いとは思いますが、それぞれのアプリケーションに合った形があるので、そこに合わせて実装しましょう 👍 
RESTful についてはぜひご自身でも調べてみて下さい！特に Rails には generate コマンドも豊富に用意されているので、それらのコマンドで作られるファイルの意味とかも一緒に見てみるといい勉強になると思います！

2018-05-10 12:11 UTC, otuhs-r commented
> ここ、現状の動きとしては問題ないので、次に進んでもいいかとは思いますが、修正やってみますか？

今回はDeviseのルーティングに乗っかって次に進んでみようかと思います。

> RESTful についてはぜひご自身でも調べてみて下さい！特に Rails には generate コマンドも豊富に用意されているので、それらのコマンドで作られるファイルの意味とかも一緒に見てみるといい勉強になると思います！

アドバイスありがとうございます。ひとつひとつ勉強してみます。

2018-05-11 01:25 UTC, pokotyamu commented
> 今回はDeviseのルーティングに乗っかって次に進んでみようかと思います。

了解しました！
が、１点抜けが合ったっぽいです 🙏 

ユーザー個別のページから更新処理をしようとした時に更新ボタンを押したら、以下のページが出てしまいます 🤔 

![image](https://user-images.githubusercontent.com/3479317/39901757-7fb51670-5505-11e8-9217-ed1e7dc01e8c.png)

path 周りが怪しそうですね。修正お願いします 🙏

2018-05-11 12:51 UTC, otuhs-r commented
確認漏れ申し訳ないです。修正しました。

2018-05-11 15:01 UTC, otuhs-r commented
herokuへのデプロイを忘れないようにGitLab-CIを用いてCI/CDパイプラインを組みました。

2018-05-14 02:34 UTC, pokotyamu commented
ちなみに heroku のアプリケーションだったら、 Automatic Deploys という機能があって、 master にマージしたタイミングで、自動デプロイさせることができますよ 👍 
参考：[Step 4: HerokuとGitHubを連携させて自動デプロイ環境を作ろう！ · Meteor アプリを Heroku にデプロイしよう！](https://j-hack.gitbooks.io/deploy-meteor-app-to-heroku/content/step4.html)

2018-05-14 02:44 UTC, pokotyamu requested changes
@otuhs-r 
ここの resource を削除よろしくおねがいします 🙏 
これが終わればマージできそう！

2018-05-14 02:44 UTC, pokotyamu commented on app/controllers/registrations_controller.rb
> +    users_me_path(resource)
今、更新が終わってた後のルーティングが `/users/me.{:id}` の形になっているのが凄く違和感ですね。この id を変えても別の user の詳細になるわけではないので、不要な設定だと思いました！
`.` 以下は基本的に拡張子のみなので、もし id を指定したい場合は `/` で区切るべきです。
今回の場合だと、show の view で current_user のみを指定しているので、ここ resource って必要ないですね 😓

2018-05-14 02:50 UTC, pokotyamu commented on app/controllers/registrations_controller.rb
> +    users_me_path(resource)
【余談】
---

自分が  `users/me` を実装するなら、 

- ルーティングは get 'users/me' として、アクション指定は変更しない
- `UsersController#me` メソッドを追加
- 今の `views/users/show.html.erb` を `views/users/me.html.erb` に変更

と言った感じで実装するかなと思います 🙋‍♂️ 
理由としては、わざわざ別名で `UsersController#show` を定義する必要ないと感じたのと、他のユーザー情報を表示したくなった時にここの実装を変えなければならないという２点ですね。

2018-05-14 11:15 UTC, otuhs-r commented on app/controllers/registrations_controller.rb
> +    users_me_path(resource)
`users/me`について、提案していただいたように変更しました。

2018-05-14 11:15 UTC, otuhs-r commented
> ここの resource を削除よろしくおねがいします 🙏

削除しました。
解説もわかりやすくありがとうございます。

2018-05-15 01:28 UTC, pokotyamu commented
動作良さそう 👍 
LGTM です！！！！

やりとり多くなりましたが、その分良いポイントでハマってくれたと思うので勉強になったと思います！
この PR を master にマージして、次に進んで下さい 🎉

2018-05-15 01:29 UTC, pokotyamu approved these changes

2018-05-15 13:00 UTC, merged