自分の面談日程の表示・登録・編集・削除機能
otuhs-r/e-navigator pull request #2
Opened 2018-05-21 10:31 UTC by otuhs-r

やりたかったこと
---
自分の面談日程を
- 登録できるようにする
- 一覧で表示できるようにする
- 編集できるようにする
- 削除できるようにする

やったこと
----

- `Interview`モデルの作成
	- `User`モデルと１対多のリレーション
- `Interview`を一覧表示するページの追加
- `Interview`の登録・編集ページの追加
- 日時を表示する際のタイムゾーンを東京に変更

動作確認方法
---
- 面談の一覧表示
	- [ ] 画面右上の`Interviews`より、面談一覧ページへいく
- 面談の登録
	- [ ] 面談一覧ページ左下`New Interview`より、面談登録ページへいく
	- [ ] 日時を入力して`Create`をクリックする
- 面談の編集
	- [ ] 面談一覧ページより、編集したい面談の`Edit`をクリックして編集ページへいく
	- [ ] 日時を変更して`Update`をクリックする
- 面談の削除
	- [ ]  面談一覧ページより、削除したい面談の`Remove`をクリック
	- [ ] 確認ダイアログの`OK`をクリックする
 
その他
---

デプロイ先：https://e-navigator-otuhs-r.herokuapp.com/

2018-05-23 01:24 UTC, pokotyamu commented
見ます 👀

2018-05-23 01:26 UTC, pokotyamu commented
プルリクエストのタイトル、０コメめっちゃ良くなりましたね 👍 

ただ、 `my_interview` というブランチ名はイマイチな感じがします 😓 
自分の面接をどうしたいのか？という部分まで表現されているとより明確になって良いと思いますよ 👍

2018-05-23 01:27 UTC, pokotyamu commented
d50e366

scaffold コマンドを使ってやったのかな？ 👍 
めっちゃ良いと思う 👍

2018-05-23 01:44 UTC, pokotyamu requested changes
適宜質問に対してコメントや修正よろしくお願いします 🙏

2018-05-23 01:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      params.require(:interview).permit(:scheduled_datetime, :accepted)
ちなみにここってなんで必要かご存知ですか？ 😄

2018-05-23 01:44 UTC, pokotyamu commented on config/application.rb
> +    config.time_zone = "Tokyo"
`Tokyo` でも設定出来ますし、 `Asia/Tokyo` でも設定できます 👍 
[RubyとRailsにおけるTime, Date, DateTime, TimeWithZoneの違い - Qiita](https://qiita.com/jnchito/items/cae89ee43c30f5d6fa2c#part-2-rails%E3%81%AE%E5%A0%B4%E5%90%88)

2018-05-23 01:44 UTC, pokotyamu commented on app/models/interview.rb
> +  enum status: { Pending: 0, Accepted: 1, Rejected: 2 }
status の enum キーは Ruby コードっぽく小文字で設定しましょ！

2018-05-23 01:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews = user.interviews.order(:scheduled_datetime)
これって古い順になるんですっけ？
例えば、新しい順にしたい時ってどうすればいいんでしたっけ？ 😄

2018-05-23 01:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> -  # GET /interviews.json
ホントに不要なコメントだったかは、ちょっと怪しいですね 🤔 
ルーティングのパスを示すという意味では、

`GET /interviews` ではなく `GET /users/:user_id/interviews` に修正するなら分かりますが...

2018-05-23 01:44 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  end
今回、 json フォーマットで返す必要なければ、以下の用に書くことができます。

```
  def create
    @interview = current_user.interviews.build(interview_params)
    if @interview.save
      redirect_to user_interviews_path(current_user.id), notice: 'Interview was successfully created.'
    else
      render :new
    end
  end
```

2018-05-23 01:45 UTC, pokotyamu commented
多分、通知が２ついっちゃってると思う 👀 

<img width="740" alt="_2018_05_23_10_41" src="https://user-images.githubusercontent.com/3479317/40399078-5a425a54-5e76-11e8-9e7e-98a2d08a1878.png">

2018-05-23 12:20 UTC, otuhs-r commented
レビューありがとうございます！

> ただ、 my_interview というブランチ名はイマイチな感じがします 😓
自分の面接をどうしたいのか？という部分まで表現されているとより明確になって良いと思いますよ 👍

次回以降のブランチ名、意識します！

> scaffold コマンドを使ってやったのかな？ 👍

はい、scaffold使いました。

> 多分、通知が２ついっちゃってると思う 👀
これは意図的ですかね？

気づきませんでした。。。修正しました。

2018-05-23 12:21 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +      params.require(:interview).permit(:scheduled_datetime, :accepted)
プルリクエストを送った時点では理解していませんでした。(scaffoldで自動生成)

調べてみた結果、
* Strong Parameters という名前の機能
* ホワイトリスト形式でリクエストパラメータを検証する仕組み

と理解しました。

今回、`Interview`モデルの `accepted` は `status` に変更したのでそれに合わせてここも修正しました。
ホワイトリスト形式のため、`permit`の引き数に`:accepted`が残っていても問題なく動いていたものと認識しました。

2018-05-23 12:21 UTC, otuhs-r commented on app/models/interview.rb
> +  enum status: { Pending: 0, Accepted: 1, Rejected: 2 }
修正しました。
同様に`User`モデルの`gender`も修正しました。

2018-05-23 12:21 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +    @interviews = user.interviews.order(:scheduled_datetime)
デフォルトでは昇順(古い順)の認識です。
新しい順は次の方法でできました😄
`@interviews = user.interviews.order(scheduled_datetime: :desc)`
`@interviews = user.interviews.order('scheduled_datetime desc')`

2018-05-23 12:21 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> -  # GET /interviews.json
前提：このコメントはscaffoldを使ったときに自動生成されたものです。

ご指摘のとおり、削除するか正しいパスに修正するか悩みました。
結論としては、ルーティングを確認すれば明らかなことをわざわざコメントに書く必要もないかなと思い削除するに至りました。

2018-05-23 12:21 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +  end
jsonで返す必要ないので提案いただいたように修正しました。

まだまだおまじない的に(というよりscaffoldにまかせて)書いている部分が多いので、それぞれ何をしているのかきちんと理解するよう努めます。

ちなみに実際のWebアプリケーションで、jsonで返したい場合ってどういうものがあるんでしょうか？APIとして公開する場合とかでしょうか？

2018-05-24 01:33 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews = user.interviews.order(:scheduled_datetime)
いいですね！
`desc` , `asc`  は SQL の用語として使うので覚えておくと良いですよ 👍 

以下、 SQL 確認メソッド(`#to_sql`)の結果

```
irb(main):010:0> user.interviews.order(scheduled_datetime: :desc).to_sql
=> "SELECT \"interviews\".* FROM \"interviews\" WHERE \"interviews\".\"user_id\" = 1 ORDER BY \"interviews\".\"scheduled_datetime\" DESC"
irb(main):012:0> user.interviews.order(:scheduled_datetime).to_sql
=> "SELECT \"interviews\".* FROM \"interviews\" WHERE \"interviews\".\"user_id\" = 1 ORDER BY \"interviews\".\"scheduled_datetime\" ASC"
```

2018-05-24 01:35 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> -  # GET /interviews.json
> 結論としては、特殊なルーティングではない＆ルーティングを確認すれば明らかなことをわざわざコメントに書く必要もないかなと思い削除するに至りました。

ナルホド!
良いと思います 👍

2018-05-24 01:36 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  end
> まだまだおまじない的に(というよりscaffoldにまかせて)書いている部分が多いので、それぞれ何をしているのかきちんと理解するよう努めます。

そうですね！いい心がけだと思います！
僕も最初はおまじない的に使ってましたが、自分だったらこう書くのになんでこのメソッド使ってるんだろ？とかって視点で調べてみると新しい発見があるかも知れません！

2018-05-24 01:39 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  end
> ちなみに実際のWebアプリケーションで、jsonで返したい場合ってどういうものがあるんでしょうか？APIとして公開する場合とかでしょうか？

おっしゃる通りです！
プロダクトのコードでも、Rails アプリケーションとして view を作らず、 Java Script でフロントを実装する際のデータのやり取りなどで、 json を使うことがあります！
必要になったときだけ実装というのが良いですね！

2018-05-24 01:43 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      params.require(:interview).permit(:scheduled_datetime, :accepted)
良い理解ですね！！！！
もう一弾理解のためのヒントとして与えるとすれば、なぜ Strong Parameters がデフォルトのメソッドとして用意されているか？みたいな点を調べてみても面白いかも知れません！

2018-05-24 01:45 UTC, pokotyamu commented
うん！動作も良さそうに思いました 👍 
rails で用意してくれてるコマンドは、 **※ 裏で何が行われているか？を理解した上で** 積極的に使っていきましょう！！！！
そうすれば、爆速で質の高いコードが実装出来ると思います 👍

2018-05-24 01:47 UTC, pokotyamu approved these changes
LGTM です 🎉 
マージして次に進んで下さい！！！

2018-05-24 03:44 UTC, merged