面接官が面接日程を承認or拒否できるようにする
otuhs-r/e-navigator pull request #3
Opened 2018-05-29 13:21 UTC by otuhs-r

## やりたかったこと

* 自分以外のユーザーの一覧をトップページに表示する
	* 各ユーザーの情報と各ユーザーの面接一覧へのリンクを表示
* 自分の面接一覧を見たときと、他人の面接一覧を見たときとで表示内容を切り替える
	* 自分：面接日程のCRUDができる
	* 他人：面接日程の承認ができる
* 他人の面接日程を承認or拒否できるようにする
	* 面接日程を選択したら、その日が承認されたことを保存＆他の日が拒否されたことを保存

## 主にやったこと

* `user#index`では、`where`句を使って自分以外のユーザーを取得するようにした
* 誰の面接一覧を表示するかによって、`interviews#index`が返すインタビュー一覧を変えるようにした
* パーシャルを使って、自分の面接一覧と、他人の面接一覧のViewを分けた
* `User`モデルに、選択された日以外のすべての面接日程を拒否状態にするメソッドを追加した

## 動作確認方法

### 事前準備
- [ ] 面接官用のアカウント(以後、A)と、面接を受ける人用のアカウント(以後、B)、計２つのアカウントを用意する
- [ ] Bで面接候補日程を作成する

### 動作確認
- [ ] Aでトップページにアクセスして、自分以外のユーザーの一覧が表示されていることを確認する
- [ ] Bの`Show Interviews`をクリックして、面接日程選択ページへいく
- [ ] 任意の日程を面接日として選択する
	* 過去の日程は選択できないようにしました
- [ ] 日程選択後、面接予定日が上部に表示されることを確認する
- [ ] トップページへ戻って、Bの`Interview Datetime`に先ほど選択した日程が表示されていることを確認する 
- [ ]  Bでログインし直して、Bの面接日程を確認する
	* 選択した日程が`Accepted`、その他の日程が`Rejected`
- [ ] 面接日程の編集または新規作成から同じ日程の面接が複数存在できないことを確認する

---
デプロイ先：https://e-navigator-otuhs-r.herokuapp.com/

2018-05-30 07:49 UTC, pokotyamu commented
👀

2018-05-30 07:50 UTC, pokotyamu commented
めっちゃきれいなプルリクエストになってる 👏  👏  👏  👏 
動作確認の書き方(事前準備、動作確認)って感じいいですね 👏  👏  👏  👏

2018-05-30 08:14 UTC, pokotyamu requested changes
@otuhs-r ロジックがしっかりモデル層にかかれていて良いコードだと思いました！
しかし何点か Rails っぽくない部分やメソッド名と中身が違いそうなものなどあったので修正よろしくお願いします！

2018-05-30 08:14 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    user = User.find(params[:user_id])
`user = User.find(params[:user_id])` が `#index`, `#update` それぞれで出てきてますね 👀 
`set_user` などでいい感じにまとめちゃいましょう！

2018-05-30 08:14 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    end
`@interviews` の取得を view 側でなく、 controller でするの良いですね 👍

2018-05-30 08:14 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    end
インデントこっちのほうが見やすさありますね 👀 
修正はおまかせします！

```ruby
    @interviews = if current_user?(@user)
                    @user.interviews.order(:scheduled_datetime)
                  else
                    @user.interviews.where(status: :pending).or(@user.interviews.where(status: :rejected)).order(:scheduled_datetime)
                  end
```

2018-05-30 08:14 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interview = User.find(params[:user_id]).interviews.find(params[:id])
ここ、 User.find を経由して面接を検索しているのって意味ありますか？
`Interview.find(params[:id])` との違いが知りたいです！

2018-05-30 08:14 UTC, pokotyamu commented on app/models/interview.rb
> +    self.status != 'pending'
enum のヘルパーをうまく使うと良さそうですね。

```
def committed?
  !pending?
end
```

みたいな感じで同様の結果を期待する事ができます！

2018-05-30 08:14 UTC, pokotyamu commented on app/models/interview.rb
> +    self.status != 'pending'
enum のヘルパーは一回調べてみるといろいろ発見があって面白いですよ！

2018-05-30 08:14 UTC, pokotyamu commented on app/models/user.rb
> +  end
モデルの実装部分で、多分 self は不要な気がします

2018-05-30 08:14 UTC, pokotyamu commented on app/models/user.rb
> +  end
面接の日時というメソッド名なのに、結果として得られているのは、**承認済み** の面接時間という感じなんですね。
ユーザーモデルの責務としては、承認済みの面接だけを返してあげるほうが、ユーザーモデルは日時の情報を知る必要ないはずなので、良さそうな気がしますね。

なんで、 accepted_interview みたいなメソッドに返るのはいかがでしょう？

2018-05-30 08:14 UTC, pokotyamu commented on db/schema.rb
> +    t.index ["user_id", "scheduled_datetime"], name: "index_interviews_on_user_id_and_scheduled_datetime", unique: true
時間でのユニーク成約良いですね 👍

2018-05-30 13:16 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +    user = User.find(params[:user_id])
`set_user` にまとめました。

2018-05-30 13:16 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +    end
たしかにそのほうが見やすいですね👀
修正しました。

2018-05-30 13:16 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +      @interview = User.find(params[:user_id]).interviews.find(params[:id])
このあたりは [Rails Tutorial の 13.1.3 ](https://railstutorial.jp/chapters/user_microposts?version=5.1#sec-user_micropost_associations)の内容を参考にしました。

>例えば次のような
> ```
> @user = users(:michael)  
> # このコードは慣習的に正しくない
> @micropost = Micropost.new(content: "Lorem ipsum", user_id: @user.id)
> ```
> という書き方 (リスト 13.4) が、次のように書き換えられます。
> 
> ```
> @user = users(:michael)
> @micropost = @user.microposts.build(content: "Lorem ipsum")
> ```

(表13.1より)
> user.microposts.find_by(id: 1) | userに紐付いていて、idが1であるマイクロポストを検索する

得られる結果としては同じだと思うのですが、どちらがいいんでしょうか？

2018-05-30 13:17 UTC, otuhs-r commented on app/models/interview.rb
> +    self.status != 'pending'
調べてみました。結構いろんなことができるんですね！ありがとうございます。

2018-05-30 13:17 UTC, otuhs-r commented on app/models/user.rb
> +  end
削除しました。

2018-05-30 13:17 UTC, otuhs-r commented on app/models/user.rb
> +  end
たしかに`interview_datetime`という名前から期待するものと実際に得られるものとに乖離がありますね。。。
提案していただいたとおり変更しました。

2018-06-04 08:03 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interview = User.find(params[:user_id]).interviews.find(params[:id])
惜しいですね！ただ、参考にした情報を書いてあるの良いと思いました 👍 

Rails チュートリアルのこれは、

```
@user = users(:michael)
@micropost = @user.microposts.build(content: "Lorem ipsum")
```

`@user` に紐づく `micropost` インスタンスを作ることを目的としています。
ここで作られる Micropost インスタンスの user カラムにはすでに `@user` に代入されているインスタンスが紐付いています。

今回の場合。

```
User.find(params[:user_id]).interviews.find(params[:id])
```

一見、これ良さそうに見えるのですが、 `interviews.find(params[:id])` としている時点で、 id をキーに検索するため、一位に決まるので不要という風に感じました。
例えば、

```
User.find(params[:user_id]).interviews.find_by(schedule: Time.today)
```

こんな感じで、特定ユーザーの面接の中でスケジュールが今日なものみたいな感じだったら、使って良いと思いました！

2018-06-04 08:05 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interview = User.find(params[:user_id]).interviews.find(params[:id])
> 得られる結果としては同じだと思うのですが、どちらがいいんでしょうか？

また、 SQL 的な視点でも User の検索で一回、 Interview の検索で一回の合計２回走ることになるので、節約の意味も込めて、 Interview.find(params[:id]) のほうがいいかなと思いました。

2018-06-04 08:07 UTC, pokotyamu commented on app/models/user.rb
> +  end
名前つけってほんと難しいですよね😓

ruby はメソッドなのか、インスタンス変数なのか、ブラックボックスになってしまう言語なので、なおさらこれでは何が返る？みたいなのを意識できるといいなと思いました 👍

2018-06-04 11:07 UTC, otuhs-r commented on app/controllers/interviews_controller.rb
> +      @interview = User.find(params[:user_id]).interviews.find(params[:id])
> 一見、これ良さそうに見えるのですが、 interviews.find(params[:id]) としている時点で、 id をキーに検索するため、一位に決まるので不要という風に感じました。

> また、 SQL 的な視点でも User の検索で一回、 Interview の検索で一回の合計２回走ることになるので、節約の意味も込めて、 Interview.find(params[:id]) のほうがいいかなと思いました。

なるほど、たしかにそのとおりだと思いました。

ところで、Rails Tutorial の表13.1にあるような、`user.microposts.find_by(id: 1)` という書き方をするとしたら、

* `user` が `id: 1` のマイクロポストを持っているかどうかわかっていなくて、
* もし `user` が持っているとしたら取得したい

場合ということですか？　( `find` じゃなくて `find_by` なのもそのため？)

> `user.microposts.find_by(id: 1)` | userに紐付いていて、idが1であるマイクロポストを検索する（表13.1より）

2018-06-05 01:39 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interview = User.find(params[:user_id]).interviews.find(params[:id])
個人的には、ユーザーに紐づくマイクロソフトを探すというのをコードから読みとけるようにするためかな？という印象を持ちましたね 👀 
僕がレビュアーなら一旦意図を聞いてからマージすると思いますね。

あと、 `find` と `find_by` の違いとしては見つからない時の挙動が違いますね。

```
[1] pry(main)> User.find(0)
  User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 0 LIMIT 1
ActiveRecord::RecordNotFound: Couldn't find User with 'id'=0
[2] pry(main)> User.find_by(id: 0)
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 0 LIMIT 1
=> nil
[3] pry(main)> User.find_by!(id: 0)
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 0 LIMIT 1
ActiveRecord::RecordNotFound: Couldn't find User
from /Users/pokotyamu/src/github.com/feedforce/app-dfplusio/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:216:in `find_by!'
```

`find_by!` とすると同じく例外を発生させることができます。

2018-06-05 02:02 UTC, pokotyamu commented
動作コード確認しました！！！！！！
良さそうですね 👍 

マージして次に進んじゃってください 🎉

2018-06-05 02:03 UTC, pokotyamu approved these changes
LGTM 🎉

2018-06-05 03:53 UTC, merged