面接日程の登録 / 承認を知らせるためのメールを送信できるようにする
otuhs-r/e-navigator pull request #4
Opened 2018-06-07 12:19 UTC by otuhs-r

やりたかったこと
---

- 指定したユーザーに面接日程の承認を依頼するメール(以後、承認依頼)を送信できるようにする
- 面接日程が承認されたら、両者にその旨を伝えるメール(以後、リマインダ)を送信する

主にやったこと
----

- `NotificationMailer` の作成
	* 承認依頼用とリマインダ用のアクション作成
- 承認依頼用とリマインダ用のビュー作成
- `interviews#update` にメイラーを呼び出す処理追加
- `InterviewsController` にメイラーを呼び出す新規アクション追加
	* ルーティングも追加

動作確認方法
---

### 事前準備

- [ ] 面接官用のアカウント(以後、A)と、面接を受ける人用のアカウント(以後、B)、計２つのアカウントを用意する
- [ ] Bで面接候補日程を作成する

### 動作確認
- [ ] 承認依頼メールを送信できる
	1. Bでログインする
	2. (Bの面接作成画面の右上) Aのメールアドレスを指定して `Request` ボタンをクリックする
	3. Aに承認依頼メールが送信されていることを確認する
- [ ] リマインダメールを送信できる
	1. Aでログインする
	2. Bの面接日程を確認する
	3. 任意の面接日程を承認する
	4. AとBの両者にリマインダメールが送信されていることを確認する

---
https://e-navigator-otuhs-r.herokuapp.com/

2018-06-08 02:35 UTC, pokotyamu commented
👀

2018-06-08 02:48 UTC, pokotyamu requested changes
@otuhs-r 動作的には良さそう!!! ただ細かいですが名前付けの部分だけ確認よろしくお願いします！

2018-06-08 02:48 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +class NotificationMailer < ApplicationMailer
`NotificationMailer` かぁ 🤔 

この名前付けだと、 `通知` が主語になっているので、今後追加される通知に関するメールが全部ここに来ちゃいますよね？
いわゆる神クラスになっちゃう危険性があるので、ここは Interview に絞った InterviewMailer とするのが良さそうですね

2018-06-08 02:48 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +  def send_reminder_to(applicant:, interviewer:)
メーラーのメソッドとして、 send つけるかどうか問題なー 💭 
僕は付けなくてもメソッドとして `確定した`  というイチ単語でいいかなという気持ちがあります。
あくまで、ここはメーラークラスのメソッドとして追加されるので。

2018-06-08 14:04 UTC, otuhs-r commented on app/mailers/notification_mailer.rb
> +class NotificationMailer < ApplicationMailer
> いわゆる神クラスになっちゃう危険性があるので、ここは Interview に絞った InterviewMailer とするのが良さそうですね

なるほど…！まったくそのとおりですね。
毎回名前の付け方とても勉強になります。ありがとうございます。

2018-06-08 14:09 UTC, otuhs-r commented on app/mailers/notification_mailer.rb
> +  def send_reminder_to(applicant:, interviewer:)
> あくまで、ここはメーラークラスのメソッドとして追加されるので。

たしかに `send` されることは明らかなので冗長ですね。

> 僕は付けなくてもメソッドとして `確定した` というイチ単語でいいかなという気持ちがあります。

メソッド名は動詞にしたいというのと、`確定する(confirmなど?)`だと中身と乖離してしまうので `remind` としてみたのですがいかがでしょうか？

2018-06-11 08:18 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +  def send_reminder_to(applicant:, interviewer:)
> メソッド名は動詞にしたいというのと、確定する(confirmなど?)だと中身と乖離してしまうので remind としてみたのですがいかがでしょうか？

remind だと、イメージ前日とかに送られるメールなのかな？みたいな気持ちになりました 👀 
自分だったら apply とかって名前をつけるかなぁ 💭

2018-06-11 08:18 UTC, pokotyamu commented
@otuhs-r 名前つけ第二弾でコメントしてみました！いかがでしょう？ 🤔 
https://github.com/otuhs-r/e-navigator/pull/4#discussion_r194322990

2018-06-11 08:45 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +  def send_reminder_to(applicant:, interviewer:)
apply じゃなくて承認するとか賛成するという意味で approve とかつけるという提案でした。
apply(申し込む) は request_to のメソッド名変更の提案としていかがでしょう？

2018-06-12 08:23 UTC, pokotyamu commented
良さそう！
改めて動作確認します！

2018-06-12 08:25 UTC, pokotyamu commented
大丈夫そうですね〜 🎉 
LGTM です！
お疲れ様でした！！！！

2018-06-12 08:49 UTC, merged